version: '3'
services:
  web_login:
    build:
      context: .
      dockerfile: Docker/app/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: production
      FLASK_SECRET: $FLASK_SECRET
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass $FLASK_SECRET
